name: .NET Core Desktop

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    # We need to run on windows as we need access to ms build.
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:

    # Checks out the code from git.
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: msbuild App1.sln /t:Restore /p:Configuration=Release
      env:
        Configuration: Release

    # Build the application to populate the obj folder with RuntimeIdentifiers
    - name: Build the application
      run: msbuild App1.sln /p:Configuration=Release /t:PackageForAndroid
      env:
        Configuration: Release
    
    # Publish APK
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: APK
        path: App1/bin/Release/com.companyname.app1.apk
        retention-days: 1
